<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>13_6_Check_communication_Expiry</name>
   <tag></tag>
   <elementGuidId>1e3b65d4-6550-495a-ae97-9766ade54c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#de7b32230aa8cb3b8b6d01b189c229c2_m_expiry_period_url_check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@cid=&quot;m_expiry_period_url_text_rcheck&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>de7b32230aa8cb3b8b6d01b189c229c2_m_expiry_period_url_check</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cid</name>
      <type>Main</type>
      <value>m_expiry_period_url_text_rcheck</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ctype</name>
      <type>Main</type>
      <value>check</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doCheckBoxVisible(this, 'de7b32230aa8cb3b8b6d01b189c229c2_m_expiry_period_url_display');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;de7b32230aa8cb3b8b6d01b189c229c2_m_expiry_period_url_check&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@cid=&quot;m_expiry_period_url_text_rcheck&quot;]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='display_de7b32230aa8cb3b8b6d01b189c229c2_']/div[2]/table/tbody/tr[2]/td[2]/div/table/tbody/tr/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/table/tbody/tr/td/input</value>
   </webElementXpaths>
</WebElementEntity>
