<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_df - test uniduplicate TEST_SHIVA_JU_da3e37</name>
   <tag></tag>
   <elementGuidId>71d27cf7-7e92-4a30-8d42-153e0eba241d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adv_sel_filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='adv_sel_filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>advfilter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adv_sel_filter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>df - test uniduplicate TEST_SHIVA_JULY - duplicate TEST_SHIVA_JULYexact email test - exact email testFPL_TEST_1 - FPL_TEST_1FPL_TEST_2 - FPL_TEST_2LARS_PHASEII_CONF_SMS_PROMO - LARS PHASE II confirmation test SMS PROMOLARS_PHASEII_CONF_SMS_WEBF - LARS PHASE II confirmation test SMS Web FlagLT_OZ_EMAIL_TEST - LT_OZ_EMAIL_TESTSUNDAY_PROMO_TEST - SUNDAY_PROMO_TESTSUNDAY_PROMO_TEST_OFF - SUNDAY_PROMO_TEST_OFFTEST - TESTTest august 250820 - Test august 250820test comm created sh - test comm created shortcutTEST JULY 24 COMM - TEST JULY 24 COMMTEST JULY COMM - TEST JULY COMMTEST JULY FIRST TEST - TEST JULY FIRST TESTTest september280920 - Test september280920test short comms - test short commstest-saloni-1 - test-saloni-1testef - short comms testTest_Add_Comm - Test_Add_Comm_TestTest_Add_Comm_New - Test_Add_Comm_New_TestTest_Comm_New - Test_Comm_NewTEST_MPESA200%_CFSMS - TEST_MPESA200%_CFSMSTEST_MPESA200%_OFFSMS - TEST_MPESA200%_OFFSMSTEST_SHIVA_JULY - TEST_SHIVA_JULYVDCP_49_Seg5_Test - VDCP_49_Seg5_Test</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adv_sel_filter&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='adv_sel_filter']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adv_sel_buffer']/div[2]/div[2]/div[2]/ul/li/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[5]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[6]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul/li/select</value>
   </webElementXpaths>
</WebElementEntity>
