<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06_16a5_Check_box_click_timings</name>
   <tag></tag>
   <elementGuidId>4d7fe0ea-cc6c-45a7-b225-6ce2aa7ce4ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ygtvt14 > div.ygtvspacer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ygtvt14']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ygtvspacer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ygtvt14&quot;)/div[@class=&quot;ygtvspacer&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ygtvt14']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/div/div/table/tbody/tr/td/div</value>
   </webElementXpaths>
</WebElementEntity>
