<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//*[@id=&quot;adv_sel_filter&quot;]/option[1]</description>
   <name>06_12e_select_first_option_as_a_communication</name>
   <tag></tag>
   <elementGuidId>8793cf33-2c50-45b4-9810-d69cce44e758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;adv_sel_filter&quot;]/option[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
