<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>009_02_A_01_Click_Firt_request_param</name>
   <tag></tag>
   <elementGuidId>7beee4fa-4c91-4f7d-b351-dd5dc74e601d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class=&quot;ygtvitem&quot;]/table/tbody/tr/td/a)[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
