<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PNG_bf0ab215290628b9c46e06359ff940b3__accaf3</name>
   <tag></tag>
   <elementGuidId>717f4be0-bffc-4bd3-b815-be3ebe78de87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bf0ab215290628b9c46e06359ff940b3_flow_type_png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bf0ab215290628b9c46e06359ff940b3_flow_type_png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bf0ab215290628b9c46e06359ff940b3_flow_type_png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bf0ab215290628b9c46e06359ff940b3_flow_type</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bf0ab215290628b9c46e06359ff940b3_flow_type_png&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bf0ab215290628b9c46e06359ff940b3_flow_type_png']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='bf0ab215290628b9c46e06359ff940b3_form']/div[3]/div[2]/ul/li[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/ul/li[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
