<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11_g_Drop_down_Default_BEST_OPTION</name>
   <tag></tag>
   <elementGuidId>95a666eb-946c-43bd-9875-5b444c77c0bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#7f2ac4600a0c52b98812ec0997273bc6_actionprimarykey</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@cid=&quot;actionprimarykey&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7f2ac4600a0c52b98812ec0997273bc6_actionprimarykey</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cid</name>
      <type>Main</type>
      <value>actionprimarykey</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cname</name>
      <type>Main</type>
      <value>Campaign</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ctype</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>actionLabelChange('7f2ac4600a0c52b98812ec0997273bc6', this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>actionLabelChange('7f2ac4600a0c52b98812ec0997273bc6', this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				 C220 - USSD_FAT_11 test-saloni-30-10-2020-1 - Copy of test-saloni-30-10-2020-1 VDCP24_DYNAMIC DEALS_BUNDLE_EXTRAS_USSD -  VDCP24_DYNAMIC DEALS_BUNDLE_EXTRAS_USSD VDCP41_DYNAMIC DEALS_INFO -  VDCP41_DYNAMIC DEALS_INFO195 - USSD_FAT_1Anandtest1 - Anandtest0001Anand_test - Anand_testaugust Training_Campaign_01 - august Training_Campaign_01Automate campaign 1509 - Automate campaign 1509bb_test - bb_testC1 - testC111 - Nidhi_Test_smsC112 - testusr1C113 - test_campaignC114 - dummycampaignC115 - sai1C116 - campaign_newC117 - Test-SureshC144 - Ns_event_listner_testC166 - testC174 - sai_camp_ussdC183 - LT_CAM_APPC184 - LT_CAM_APPC189 - sai_ussd_camC190 - campaign_saiC191 - USSD_FATC196 -  USSD_FAT_1C197 - USSD_FAT_2C198 - USSD_FAT_3C199 - USSD_FAT_4C211 - VDCP_43&amp;VDCP_44_TESTC212 - VDCP_43&amp;VDCP_44_TEST_FAT1C213 - VDCP_43&amp;VDCP_44_TEST_FAT2C214 - VDCP_43&amp;VDCP_44_TEST_FAT3C215 - VDCP_43&amp;VDCP_44_TEST_UATC217 - USSD_FAT_10C218 - Ramin testC219 - Ra test 2C221 - USSD_FAT_12C222 - USSD_FAT_13C262 - sai_VDCP_43&amp;VDCP_44_TESTC263 - sai2_VDCP_43&amp;VDCP_44_TESTC264 - sai2_VDCP_43&amp;VDCP_44_TESTC291 - ASC296 - VCDP_TEST_01C304 - TEST_SIVAC307 - TEST_JUNE-12C316 - NEW_campaignC317 - TEST JULY 22C359 - Test septemberC363 - Test CLMS septemberC383 - DR_Test_PKOWAC402 - test sssC41 - IVR_OUTBOUND_CAM_1C469 - automation january 1301C471 - This campaign start and stopC472 - This campaign for Start and restartC63 - LT_TEST_MESSAGEC83 - LT_TEST_RWD_DDC84 - LT_TEST_RWD_DD_02C90 - NS_IVRC91 - Copy of NS_IVRC94 - Uday TestC95 - LT TEST MRC97 - campaign anil 22C99 - AK test 001C999 - C999CamAppro2 - CamAppro2CamAppro3 - CamAppro3campaignapproval_test - campaignapproval_testCampaign_Test_Split - Campaign_Test_Splitcam_test_CampApprove - cam_test_CampApproveCHK_RES_TEST29062018 - CHK_RES_TEST29062018CHK_RES_TEST29062018_2 - CHK_RES_TEST29062018_2CHK_RES_TEST29062018_2_New - CHK_RES_TEST29062018_2_NewCHK_RES_TEST29062018_2_New2 - CHK_RES_TEST29062018_2_New2CHK_RES_TEST29062018_3 - CHK_RES_TEST29062018_3CHK_RES_TEST_10_07 - CHK_RES_TEST_10_07CHK_RES_TEST_16_07 - CHK_RES_TEST_16_07CHK_RES_TEST_17_07 - CHK_RES_TEST_17_07CHK_RES_TEST_17_07_New - CHK_RES_TEST_17_07_NewCHK_RES_TEST_23_07_New - CHK_RES_TEST_23_07_NewCLMS_PHP_UPGRADE - CLMS_PHP_UPGRADECopy of C111 - Copy of Nidhi_TestCopy of C144 - Copy of Ns_event_listner_testCopy of C166 Ramin - Copy of test RaminCopy of C211 - Copy of VDCP_43&amp;VDCP_44_TESTCopy of C214 - Copy of VDCP_43&amp;VDCP_44_TEST_FAT3Copy of C316 - Copy of NEW_campaignCopy of C359 - Copy of Test septemberCopy of C41 - Copy of IVR_OUTBOUND_CAM_1Copy of C460 - Modify this campaignCopy of C469 - This is modified campaign to deleteCopy of C63 - Copy of LT_TEST_MESSAGECopy of C84 - Copy of LT_TEST_RWD_DD_02Copy of C91 - Copy of Copy of NS_IVRCopy of C95 - Copy of LT TEST MRCopy of campaignapproval_test - Copy of campaignapproval_testCopy of Copy of C111 - Copy of Copy of Nidhi_TestCopy of Copy of C63 - Copy of Copy of LT_TEST_MESSAGECopy of Copy of C84 - Copy of Copy of LT_TEST_RWD_DD_02Copy of Copy of C91 - Copy of Copy of Copy of NS_IVRCopy of Copy of C95 - Copy of Copy of LT TEST MRCopy of Copy of Copy of C95 - Copy of Copy of Copy of LT TEST MRCopy of Copy of Copy of Copy of Copy of VDCP_26_Handset_Bundle_Offer - Copy of Copy of Copy of Copy of Copy of VDCP_26_Handset_Bundle_OfferCopy of Copy of Copy of Copy of VDCP_26_Handset_Bundle_Offer - Copy of Copy of Copy of Copy of VDCP_26_Handset_Bundle_OfferCopy of Copy of Copy of LT_MPESA_B2C - Copy of Copy of Copy of LT_MPESA_B2CCopy of Copy of Copy of LT_TEST_114 - Copy of Copy of Copy of LT_TEST_114Copy of Copy of Copy of TEST_CASE - Copy of Copy of Copy of TEST_CASECopy of Copy of Copy of VDCP_26_Handset_Bundle_Offer - Copy of Copy of Copy of VDCP_26_Handset_Bundle_OfferCopy of Copy of LT_MPESA_01 - Copy of Copy of LT_MPESA_01Copy of Copy of LT_MPESA_B2C - Copy of Copy of LT_MPESA_B2CCopy of Copy of LT_TEST_114 - Copy of Copy of LT_TEST_114Copy of Copy of QA_Commn_Benchmarking - Copy of Copy of QA_Commn_BenchmarkingCopy of Copy of Test august 260820  - Copy of Copy of Test august 260820Copy of Copy of Test august 260820 Multi - Copy of Copy of Test august 260820 MultiCopy of Copy of Test october 30 - Copy of Copy of Test october 30Copy of Copy of TEST_CASE - Copy of Copy of TEST_CASECopy of Copy of VCDRC979_campaign_approval - Copy of Copy of VCDRC979_campaign_approvalCopy of Copy of VCDRC_102_NonDATA_RevBand2 - Copy of Copy of VCDRC_102_NonDATA_RevBand2 ($2.01-$5)Copy of Copy of VDCP24_DYNAMIC DEALS_RECHARGE_GIFT_USSD - Copy of VDCP24_DYNAMIC DEALS_RECHARGE_GIFT_USSD_MULTICopy of Copy of VDCP_26_Handset_Bundle_Offer - Copy of Copy of VDCP_26_Handset_Bundle_OfferCopy of delete test january 11012021 - Copy of delete test january 11012021Copy of Dup114_check - Copy of Dup114_checkCopy of JOSE_TEST - Copy of JOSE_TESTCopy of LT_MPESA_01 - Copy of LT_MPESA_01Copy of LT_MPESA_B2C - Copy of LT_MPESA_B2CCopy of LT_TEST_114 - Copy of LT_TEST_114Copy of LT_TEST_COMMS - Copy of LT Testing CommsCopy of LT_USSD_TWO_WAY_TEST - Copy of LT_USSD_TWO_WAY_TESTCopy of NBA_TEST_MASTER - Copy of NBA_TEST_MASTERCopy of Nidhi_Test_ussd_comm - Copy of Nidhi_Test_ussd_commCopy of NS_IVR_20D_Bundle - Copy of NS_IVR_20D_BundleCopy of NS_test_1223 - Copy of NS_test_1223Copy of QA_Commn_Benchmarking - Copy of QA_Commn_BenchmarkingCopy of RS_114_TEST_Dup_RS - Copy of Copy of RS_114_TESTCopy of Test august 250820 - Copy of Test august 250820Copy of Test august 260820  - Copy of Test august 260820Copy of Test august 260820 Adjust Account Reward - Copy of Test august 260820 Adjust Account RewardCopy of Test august 260820 Multi - Copy of Test august 260820 MultiCopy of Test CLMS september duplicate - Copy of Test CLMS september duplicateCopy of test january 11012021 - Copy of test january 11012021Copy of test october 1609 - Copy of test october 1609Copy of Test october 30 - Copy of Test october 30Copy of Test october modify - Copy of Test october modifyCopy of Test september 10092020 - Copy of Test september 10092020Copy of TEST03072018 - Copy of TEST03072018Copy of TestCampaign_29MAR2018 - Copy of TestCampaign_29MAR2018Copy of TEST_CASE - Copy of TEST_CASECopy of Training_Campaign_01 - Copy of Training_Campaign_01Copy of Trigger_Test - Copy of Trigger_TestCopy of VCDRC979_campaign_approval - Copy of VCDRC979_campaign_approvalCopy of VCDRC_102_NonDATA_RevBand2 - Copy of VCDRC_102_NonDATA_RevBand2 ($2.01-$5)Copy of VCDRC_127_NonDataUser_300MB_Weekly - Copy of VCDRC_127_NonDataUser_300MB_WeeklyCopy of VDCP24_DYNAMIC DEALS_BUNDLE_EXTRAS_USSD - VDCP24_DYNAMIC DEALS_BUNDLE_EXTRAS_USSD_MULTICopy of VDCP24_DYNAMIC DEALS_RECHARGE_DISC_USSD - VDCP24_DYNAMIC DEALS_RECHARGE_DISC_USSD_MULTICopy of VDCP24_DYNAMIC DEALS_RECHARGE_EXTRAS_USSD - Copy of VDCP-24 DD Recharge Bundles Extras USSDCopy of VDCP24_DYNAMIC DEALS_RECHARGE_EXTRAS_USSD_UAT - Copy of Copy of Copy of VDCP-24 DD Recharge Bundles Extras USSDCopy of VDCP24_DYNAMIC DEALS_RECHARGE_GIFT_USSD - VDCP24_DYNAMIC DEALS_RECHARGE_GIFT_USSD_MULTICopy of VDCP24_DYNAMIC DEALS_RECHARGE_RATECUT_USSD - VDCP24_DYNAMIC DEALS_RECHARGE_RATECUT_USSD_MULTICopy of VDCP35_DYNAMIC DEALS_WARNING  - Copy of VDCP35_DYNAMIC DEALS_WARNINGCopy of VDCP_26_Handset_Bundle_Offer - Copy of VDCP_26_Handset_Bundle_OfferCopy of VDCP_29_Sunday_Promo_Decile1 - Copy of VDCP_29_Sunday_Promo_Decile1Copy of VDCP_87_J4U_Data_Bundle_Reminder_USSD - Copy of VDCP_87_J4U_Data_Bundle_Reminder_USSDData_Dormant_Seg1(25MB)_$0.5 - Data_Dormant_Seg1(25MB)_$0.5delete test january 11012021 - delete test january 11012021Dummy_CHK_RES_TEST29062018 - Dummy_CHK_RES_TEST29062018Dup114 - Dup114Dup114Dup114Dup114 - Dup114Dup114Dup114Dup114_114 - Copy of Dup114Dup114_114_Check - Copy of Copy of Dup114Dup114_check - Dup114_checkduplicated campaign - duplicated campaignDup_TEST_JUNE-12-01 - Dup_TEST_JUNE-12-01ENBA testing january - ENBA testing januaryENBA testing january 2 - ENBA testing january 2ETAN_TEST_1 - ETAN_TEST_1FPL_TC10 - FPL_TC10FPL_TEST_1 - FPL_TEST_1FPL_TEST_2 - FPL_TEST_2FPL_TEST_DMART_1 - FPL_TEST_DMART_1IVR Campaign D - IVR Campaign DIVR Campaign E - IVR Campaign EIVR Campaign UAT - IVR Campaign UATIVR01 - IVR Campaign AIVR02 - IVR Campaign BIVR03 - IVR Campaign CIVR_1DONNET_Bundle - IVR_1DONNET_BundleIVR_1D_Bundle - IVR_1D_BundleIVR_20D_Bundle - IVR_20D_BundleIVR_25COFFNET_Bundle - IVR_25COFFNET_BundleIVR_25CONNET_Bundle - IVR_25CONNET_BundleIVR_25CSMS_Bundle - IVR_25CSMS_BundleIVR_25C_Bundle - IVR_25C_BundleIVR_2D_Bundle - IVR_2D_BundleIVR_30CSMS_Bundle - IVR_30CSMS_BundleIVR_50COFFNET_Bundle - IVR_50COFFNET_BundleIVR_50CONNET_Bundle - IVR_50CONNET_BundleIVR_50C_Bundle - IVR_50C_BundleIVR_Loyalty_01 - IVR_Loyalty_01JOSETEST1 - JOSETEST1JOSE_TEST - JOSE_TESTLT_IVR_LOYALTY - LT IVR LOYALTYLT_MPESA_01 - LT_MPESA_01LT_MPESA_B2C - LT_MPESA_B2CLT_MPESA_B2C_QueryCustBalance - LT_MPESA_B2C_QueryCustBalanceLT_TEST_114 - LT_TEST_114LT_TEST_COMMS - LT Testing CommsLT_USSD_TWO_WAY_TEST - LT_USSD_TWO_WAY_TESTMPESA_TEST_ALL_APIS - MPESA_TEST_ALL_APISMPESA_Transact_ID - MPESA_Transact_IDNBA_MASTER - NBA_MASTERNBA_REMIND_MASTER - NBA_REMIND_MASTERNBA_TEST_MASTER - NBA_TEST_MASTERNew Campaign Test For Approval Process - New Campaign Test For Approval ProcessNidhi_Test_ussd_comm - Nidhi_Test_ussd_commNS_C84 -  NS_TEST_RWD_DD_02NS_Campaign - NS_CampaignNS_campaign_approval - NS_campaign_approvalNs_event - Ns_eventNS_IVR_20D_Bundle - NS_IVR_20D_BundleNS_IVR_Loyaltity_Eligibility - NS_IVR_Loyaltity_EligibilityNS_test_1223 - NS_test_1223NS_test_123 - NS_test_123NS_TEST_COMMS - NS Testing CommsNS_VCRDC_1184_Campaign - NS_VCRDC_1184_CampaignNS_VCRDC_Test_Trigger_NextRun - NS_VCRDC_Test_Trigger_NextRunNS_VDDD_58 - NS_VDDD_58QA_Commn_Benchmarking - QA_Commn_BenchmarkingQA_Multi_etry_Benchmarking - QA_Multi_etry_BenchmarkingQA_Rwd_Benchmarking - QA_Rwd_BenchmarkingQA_Sgl_etry_Benchmarking - QA_Sgl_etry_Benchmarkingra1 - ra test 1RS_06FEB - RS_06FEBRS_114_TEST - RS_114_TESTRS_114_TEST_27Jan - RS_114_TEST_27JanRS_114_TEST_Dup - Copy of RS_114_TESTSAI_VCRDC_1109_Campaign - SAI_VCRDC_1109_CampaignShruti_Event_Test - Shruti_Event_TestSimple Camp - Simple CampSIMPLE_CAMPAIGN - SIMPLE_CAMPAIGNSuresh-Dec12 - Suresh-Dec12Suresh-Dec12-Dup - Suresh-Dec12-Duptest august 1609 - test august 1609Test august 250820 - Test august 250820Test august 260820  - Test august 260820Test august 260820 Adjust Account Reward - Test august 260820 Adjust Account RewardTest august 260820 Multi - Test august 260820 MultiTest Campaign 07/07/2016 - Test Campaign 07/07/2016Test CLMS september duplicate - Test CLMS september duplicateTest CLMS september real - Test CLMS september realtest december 1609 - test december 1609test january 11012021 - test january 11012021Test November - Test NovemberTest November 01 - Test November 01test november 1609 - test november 1609test october 1609 - test october 1609Test october 30 - Test october 30Test october 30 multi - Test october 30 multiTest october modify - Test october modifyTest of C215 - Test of VDCP_43&amp;VDCP_44_TEST_UATTest september 10092020 - Test september 10092020test september 1609 - test september 1609Test september 260820  - Test september 260820 test shiva october - test shiva octobertest shiva october 05 - test shiva october 05test shiva october 06 - test shiva october 06Test UK - TestUKtest-saloni-30-10-2020 - test-saloni-30-10-2020Test-Suresh - Test-Sureshtest001 - test001TestCampaign_29MAR2018 - TestCampaign_29MAR2018testtesttest123 - testTEST_12JULY2018 - TEST_12JULY2018TEST_29062018 - TEST_29062018TEST_3_MPESA_CAMPAIGN - TEST_3_MPESA_CAMPAIGNTEST_CAMPAIGN_TRANS_ID - TEST_CAMPAIGN_TRANS_IDTest_Cam_23032018 - Test_Cam_23032018TEST_CASE - TEST_CASETEST_CLMS_JUNE - TEST_CLMS_JUNETEST_REWARD - TEST_REWARDTest_ussd_comm - Test_ussd_commTEST_VDCP_82_EVERY_WIN_100FC - TEST_VDCP_82_EVERY_WIN_100FCTEST_VDCP_82_EVERY_WIN_1500FC - TEST_VDCP_82_EVERY_WIN_1500FCTEST_VDCP_82_EVERY_WIN_500FC - TEST_VDCP_82_EVERY_WIN_500FCTK_Mobile_Financial_Services - TK_Mobile_Financial_ServicesTraining12345 - Training12345Training_30MAR2018 - Training_30MAR2018Training_Campaign_01 - Training_Campaign_01Trigger_Test - Trigger_TestTrigger_Test_Final - Trigger_Test_FinalUpSell_Voice_AllNet_$20 to $50_$1 - UpSell_Voice_AllNet_$20 to $50_$1UpSell_Voice_AllNet_$5 to $20_$0.5 - UpSell_Voice_AllNet_$5 to $20_$0.5UpSell_Voice_AllNet_$50+_$5 - UpSell_Voice_AllNet_$50+_$5USSD_1 - USSD_1USSD_2 - USSD_2USSD_3 - USSD_3ussd_test1 - ussd_test1USSD_UAT_1 - USSD_UAT_1VCDRC979_campaign_approval - VCDRC979_campaign_approvalVCDRC_102_NonDATA_RevBand2 - VCDRC_102_NonDATA_RevBand2 ($2.01-$5)VCDRC_105_Voice_Onnet_Band5(LowArpu to $0.15) - VCDRC_105_Voice_Onnet_Band5(LowArpu to $0.15)VCDRC_119_UpSell_Voice_$0.15 - VCDRC_119_UpSell_Voice_$0.15VCDRC_121_Voice_Allnet_Seg1($0 to $5) - VCDRC_121_Voice_Allnet_Seg1($0 to $5)VCDRC_121_Voice_Allnet_Seg2($5 to $20) - VCDRC_121_Voice_Allnet_Seg2($5 to $20)VCDRC_127_NonDataUser_300MB_Weekly - VCDRC_127_NonDataUser_300MB_WeeklyVCDRC_70_Band3_SegmentC - VCDRC_70_RCH_LowARPU_SegmentCVCDRC_92_NonDATA_RevBand2 - VCDRC_92_NonDATA_RevBand2 ($2.01-$5)VCDRC_Data_Dormant_Seg1(25MB)_$0.5 - VCDRC_Data_Dormant_Seg1(25MB)_$0.5VCDRC_UpSell_Voice_AllNet_$20 to $50_$1 - VCDRC_UpSell_Voice_AllNet_$20 to $50_$1VCDRC_UpSell_Voice_AllNet_$5 to $20_$0.5 - VCDRC_UpSell_Voice_AllNet_$5 to $20_$0.5VCDRC_UpSell_Voice_AllNet_$50+_$5 - VCDRC_UpSell_Voice_AllNet_$50+_$5VCDRC_UpSell_Voice_AllNet_0 to $5_$0.25 - VCDRC_UpSell_Voice_AllNet_0 to $5_$0.25VDCP24_DD_PRODUCT_TESTING - VDCP24_DD_PRODUCT_TESTINGVDCP24_DYNAMIC DEALS_BUNDLE_EXTRAS_USSD - VDCP24_DYNAMIC DEALS_BUNDLE_EXTRAS_USSDVDCP24_DYNAMIC DEALS_RECHARGE_BOR_1D_USSD - VDCP24_DYNAMIC DEALS_RECHARGE_BOR_1D_USSD_MULTIVDCP24_DYNAMIC DEALS_RECHARGE_BOR_2D_USSD - VDCP24_DYNAMIC DEALS_RECHARGE_BOR_2D_USSD_MULTIVDCP24_DYNAMIC DEALS_RECHARGE_BOR_USSD - VDCP24_DYNAMIC DEALS_RECHARGE_BOR_USSDVDCP24_DYNAMIC DEALS_RECHARGE_DISC_USSD - VDCP24_DYNAMIC DEALS_RECHARGE_DISC_USSDVDCP24_DYNAMIC DEALS_RECHARGE_EXTRAS_USSD_UAT - VDCP-24 DD Recharge Bundles Extras USSDVDCP24_DYNAMIC DEALS_RECHARGE_GIFT_USSD - VDCP24_DYNAMIC DEALS_RECHARGE_GIFT_USSDVDCP24_DYNAMIC DEALS_RECHARGE_RATECUT_USSD - VDCP24_DYNAMIC DEALS_RECHARGE_RATECUT_USSDVDCP24_DYNAMIC_DEALS_RECHARGE_EXTRAS_USSD - VDCP-24 DD Recharge Bundles Extras USSDVDCP33_DYNAMIC DEALS_CUST ELIGIBILITY CHECK - VDCP33_DYNAMIC DEALS_CUST ELIGIBILITY CHECKVDCP34_DYNAMIC DEALS_WELCOME - VDCP34_DYNAMIC DEALS_WELCOMEVDCP35_DYNAMIC DEALS_WARNING  - VDCP35_DYNAMIC DEALS_WARNINGVDCP42_DYNAMIC DEALS_GET DEAL - VDCP42_DYNAMIC DEALS_GET DEALVDCP_116_vodacom_jumping - VDCP_116_vodacom_jumpingVDCP_17_Data_Dormant_120Min_NIGTH - VDCP_17_Data_Dormant_120Min_NIGTHVDCP_19_Inactivity_7days_5SMS_V4 - VDCP_19_Inactivity_7days_5SMS_V4VDCP_26_Handset_Bundle_Offer - VDCP_26_Handset_Bundle_OfferVDCP_29_Sunday_Promo_Decile1 - VDCP_29_Sunday_Promo_Decile1VDCP_83_J4U monthly_bundles_ALLNET_2500cents_30day - VDCP_83_J4U monthly_bundles_ALLNET_2500cents_30dayVDCP_87_J4U_Data_Bundle_Reminder_USSD - VDCP_87_J4U_Data_Bundle_Reminder_USSDVDCP_87_J4U_Data_Bundle_Reminder_USSD_$ 0.30 - VDCP_87_J4U_Data_Bundle_Reminder_USSD_$ 0.30VDCP_Regional_Bundles_60_Segment_3 - VDCP_Regional_Bundles_60_Segment_3VDCP_TEST_CLMS - VDCP_TEST_CLMSVDCP_TEST_CLMS_01 - VDCP_TEST_CLMS_01VDRCP_DROP_CALLS_DAILY_SEG1_5SMS - VDRCP_DROP_CALLS_DAILY_SEG1_5SMS			</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7f2ac4600a0c52b98812ec0997273bc6_actionprimarykey&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@cid=&quot;actionprimarykey&quot;]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='display_7f2ac4600a0c52b98812ec0997273bc6_']/div[2]/table/tbody/tr/td[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action Details - Campaign'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch ID:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div[2]/table/tbody/tr/td[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
